export const mockColumns = [
  {
    title: '字段名',
    dataIndex: 'name',
    type: 'text',
    editable: true,
  },
  {
    title: '字段详细描述',
    dataIndex: 'description',
    type: 'text',
    editable: true,
  },
  {
    title: '参数类型',
    dataIndex: 'type',
    type: 'text',
    editable: true,
  },
  {
    title: '是否必须',
    dataIndex: 'require',
    type: 'checkbox',
    editable: true,
  },
  {
    title: '是否唯一',
    dataIndex: 'only',
    type: 'checkbox',
    editable: true,
  },
  {
    title: '是否可见',
    dataIndex: 'isShow',
    type: 'checkbox',
    editable: true,
  },
  {
    title: '默认值',
    dataIndex: 'defaultValue',
    type: 'text',
    editable: true,
  },
];

export const mockTableData = [
  {
    name: 'uid',
    description: '用户唯一标识',
    type: 'string',
    require: true,
    only: false,
    isShow: true,
    defaultValue: '系统变量',
    id: 1,
  },
  {
    name: 'u2d',
    description: '用户唯2标识',
    type: 'string',
    require: false,
    only: false,
    isShow: false,
    defaultValue: '系统变量',
    id: 2,
  },
  {
    name: 'username',
    description: '用户名',
    type: 'string',
    require: true,
    only: true,
    isShow: true,
    defaultValue: '',
    id: 3,
  },
  {
    name: 'password',
    description: '密码',
    type: 'string',
    require: true,
    only: false,
    isShow: false,
    defaultValue: '',
    id: 4,
  },
  {
    name: 'email',
    description: '电子邮箱',
    type: 'string',
    require: false,
    only: true,
    isShow: true,
    defaultValue: '',
    id: 5,
  },
  {
    name: 'age',
    description: '年龄',
    type: 'number',
    require: false,
    only: false,
    isShow: true,
    defaultValue: '18',
    id: 6,
  },
  {
    name: 'gender',
    description: '性别',
    type: 'string',
    require: false,
    only: false,
    isShow: true,
    defaultValue: '男',
    id: 7,
  },
  {
    name: 'address',
    description: '地址',
    type: 'string',
    require: false,
    only: false,
    isShow: true,
    defaultValue: '',
    id: 8,
  },
  {
    name: 'phone',
    description: '电话号码',
    type: 'string',
    require: false,
    only: false,
    isShow: true,
    defaultValue: '',
    id: 9,
  },
  {
    name: 'status',
    description: '状态',
    type: 'boolean',
    require: false,
    only: false,
    isShow: true,
    defaultValue: 'true',
    id: 10,
  },
  {
    name: 'createdAt',
    description: '创建时间',
    type: 'date',
    require: true,
    only: false,
    isShow: true,
    defaultValue: '当前时间',
    id: 11,
  },
  {
    name: 'updatedAt',
    description: '更新时间',
    type: 'date',
    require: false,
    only: false,
    isShow: true,
    defaultValue: '当前时间',
    id: 12,
  },
  {
    name: 'role',
    description: '角色',
    type: 'string',
    require: true,
    only: false,
    isShow: true,
    defaultValue: 'user',
    id: 13,
  },
  {
    name: 'permissions',
    description: '权限列表',
    type: 'array',
    require: false,
    only: false,
    isShow: false,
    defaultValue: '[]',
    id: 14,
  },
  {
    name: 'isAdmin',
    description: '是否管理员',
    type: 'boolean',
    require: false,
    only: false,
    isShow: true,
    defaultValue: 'false',
    id: 15,
  },
];

export const AddParams = [
  {
    label: '字段名称',
    dataIndex: 'name',
    type: 'Input',
    rules: [{ required: true, message: '请输入字段名称' }],
  },
  {
    label: '字段值',
    dataIndex: 'value',
    type: 'Input',
    rules: [{ required: true, message: '请输入字段值' }],
  },
  {
    label: '字段展示类型',
    dataIndex: 'type',
    type: 'Select',
    options: [
      { label: '字符串', value: 'Input' },
      { label: '复选框', value: 'Checkbox' },
      { label: '单选框', value: 'Radio' },
      { label: '选择框', value: 'Select' },
      { label: '时间选择器', value: 'DatePicker' },
      { label: '时间范围选择', value: 'RangePicker' },
    ],
    rules: [{ required: true, message: '请选择字段展示类型' }],
  },
  {
    label: '字段排序',
    dataIndex: 'sort',
    type: 'Input',
  },
  {
    label: '字段描述',
    dataIndex: 'desription',
    type: 'TextArea',
  },
];
